server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: /3o3/swagger.html

logging:
  level:
    org.springframework.web.reactive.function.client: DEBUG

scrap:
  base-url: ""
  end-point: ""
  api-key: ""

encryption:
  secret-key: MySecretKey12345

